### PR TITLE
Chase login tests

### PR DESCRIPTION
**Pull request by CAndreas7**

### CODE REVIEW

**Comment by CAndreas7** [comment]
Still want to add more login tests just want to see if these make sense before doing more.

**Review by ethannieskes — APPROVED** [review]
Looks good.  Does the original GoodTest need a follow=True?

**Comment by CAndreas7** [comment]
Whoops don't think I "need" it but it's probably smart to add it anyway

**Review by SlinkyGoat — APPROVED** [review]
running correctly now, make sure future pushes are runnable

**Pull request merged**
